services:
    davidiq.forumapi.controller:
        class: davidiq\forumapi\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    davidiq.forumapi.listener:
        class: davidiq\forumapi\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
